#!/usr/bin/env python3
# MISSION: Set up the installer.
# STATUS: Production
# VERSION: 1.0.1
# NOTES: Generated by A.I, but tagged by the installed package.
# DATE: 2026-01-18 03:34:31
# FILE: setup.py
# AUTHOR: Randall Nagy
#
from pathlib import Path
from setuptools import setup

# This setup.py is provided as an alternative to declarative configuration.
# It mirrors the metadata in setup.cfg so you can build/install with:
#   python setup.py sdist bdist_wheel
# or with pip:
#   pip install .

ROOT = Path(__file__).parent

long_description = ""
readme = ROOT / "README.md"
if readme.exists():
    long_description = readme.read_text(encoding="utf-8")

setup(
    name="beheaded",
    version="0.1.0",
    description="Manage standardized header comments in Python scripts (BeHeaded).",
    long_description=long_description,
    long_description_content_type="text/markdown",
    author="BeHeaded Maintainers",
    author_email="maintainers@example.com",
    license="MIT",
    py_modules=["beheaded"],
    python_requires=">=3.8",
    install_requires=[
        # Add runtime requirements here if needed, e.g. "requests>=2.0"
    ],
    entry_points={
        "console_scripts": [
            "beheaded = beheaded:cli_main",
        ],
    },
    include_package_data=True,
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Software Development :: Documentation",
    ],
)
